# Generated by Django 2.0 on 2018-03-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agency',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
