# Generated by Django 2.0 on 2018-03-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstlogin',
            field=models.BooleanField(default=True),
        ),
    ]
